### ISSUE TITLE
Question for output BED

### ISSUE THREAD

**Issue by dahun73** [skrakau/PureCLIP#17] opened 2020-06-08 06:03 UTC
Hello
I'm Dahun for researcher bioinformatics.

As I first use PureCLIP, output BED file is something wrong.
I used command like this:
pureclip -i <target bam file> -bai <target bai file> -ibam <input control bam > -ibai <input control bai> -g ~/BioResource/Reference/mm10.gencode.fa -nt 10 -o PureCLIP.crosslink_sites.bed 

In this output file, there are 96,046 crosslink sites. I think it is something wrong.
When I open this BED file, the result is like this:

chr1	3019360	3019361	3	3.72365	+	[score_CL=3.72365;score_E=19.452;score_B=19.2239;score_UC=3.72365]
chr1	3113099	3113100	3	5.61987	+	[score_CL=5.61987;score_E=24.4765;score_B=24.8381;score_UC=5.61987]
chr1	3119577	3119578	3	3.72366	+	[score_CL=3.72366;score_E=24.4677;score_B=21.0672;score_UC=3.72366]
chr1	3164442	3164443	3	5.61987	+	[score_CL=5.61987;score_E=24.4765;score_B=24.8381;score_UC=5.61987]
chr1	3285514	3285515	3	9.34243	+	[score_CL=9.34243;score_E=34.0303;score_B=35.5042;score_UC=9.34243]
...
...

It has just 1 bp binding site. All the binding sites have same length.
Would you let me know the reason why that result comes out?

Thank you!

**Comment by skrakau** [comment] 2020-06-11 18:58
Hi Dahun,

as the name of your output file says it contains crosslink sites, and they have a single-nucleotide resolution. 
Please also check the [output section of the PureCLIP tutorial](https://pureclip.readthedocs.io/en/latest/PureCLIPTutorial/output.html). Note that also a lot of the binding regions (you can retrieve with the `-or` parameter) will be only 1bp long, since they are merged crosslink sites and the length thus depends on the number of crosslink sites within a certain distance. Since PureCLIP was designed to detect crosslink sites, this is intended.

Best,
Sabrina

**Closed as completed by skrakau** 2020-06-11 18:58 UTC
